version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - sphinx-apidoc -f -o ./docs/toolbox/ ./src/communicity_toolbox/toolbox/ *setup*

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: requirements.txt